minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
trustLockfile: false
blockExoticSubdeps: true
resolutionMode: time-based
engineStrict: true
strictPeerDependencies: true
pmOnFail: error
verifyDepsBeforeRun: error
strictDepBuilds: true
dangerouslyAllowAllBuilds: false
strictSsl: true
verifyStoreIntegrity: true
strictStorePkgContentCheck: true
preferFrozenLockfile: true
savePrefix: ""
