apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitai.fullname" . }}-web
  labels:
    {{- include "gitai.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "gitai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
